import { Zap, Shield, Activity, Sparkles, Wind, Flame, Droplets, Leaf, Moon, Sun, Ghost, Bug, Mountain, Gem, Crosshair, Target } from 'lucide-react';

export const TYPE_COLORS: Record<string, string> = {
  fire: 'bg-orange-600 text-white border-orange-400 shadow-orange-500/20',
  water: 'bg-blue-600 text-white border-blue-400 shadow-blue-500/20',
  grass: 'bg-emerald-600 text-white border-emerald-400 shadow-emerald-500/20',
  electric: 'bg-yellow-500 text-slate-950 border-yellow-300 shadow-yellow-500/20',
  psychic: 'bg-pink-600 text-white border-pink-400 shadow-pink-500/20',
  ice: 'bg-cyan-400 text-slate-950 border-cyan-200 shadow-cyan-500/20',
  dragon: 'bg-indigo-700 text-white border-indigo-500 shadow-indigo-500/20',
  dark: 'bg-slate-800 text-white border-slate-600 shadow-slate-900/20',
  fairy: 'bg-rose-400 text-white border-rose-200 shadow-rose-500/20',
  normal: 'bg-slate-400 text-slate-950 border-slate-300 shadow-slate-400/20',
  fighting: 'bg-red-700 text-white border-red-500 shadow-red-500/20',
  flying: 'bg-sky-400 text-slate-950 border-sky-200 shadow-sky-500/20',
  poison: 'bg-purple-600 text-white border-purple-400 shadow-purple-500/20',
  ground: 'bg-amber-700 text-white border-amber-500 shadow-amber-500/20',
  rock: 'bg-yellow-800 text-white border-yellow-600 shadow-yellow-700/20',
  bug: 'bg-lime-600 text-white border-lime-400 shadow-lime-500/20',
  ghost: 'bg-violet-800 text-white border-violet-600 shadow-violet-500/20',
  steel: 'bg-slate-500 text-white border-slate-300 shadow-slate-500/20',
};

export const TYPE_ICONS: Record<string, any> = {
  fire: Flame,
  water: Droplets,
  grass: Leaf,
  electric: Zap,
  psychic: Sparkles,
  ice: Wind,
  dragon: Shield,
  dark: Moon,
  fairy: Sun,
  normal: Activity,
  fighting: Crosshair,
  flying: Wind,
  poison: Activity,
  ground: Mountain,
  rock: Gem,
  bug: Bug,
  ghost: Ghost,
  steel: Shield,
};

export const TYPE_CHART: Record<string, { double: string[], half: string[], zero: string[] }> = {
  normal: { double: ['fighting'], half: [], zero: ['ghost'] },
  fire: { double: ['water', 'ground', 'rock'], half: ['fire', 'grass', 'ice', 'bug', 'steel', 'fairy'], zero: [] },
  water: { double: ['electric', 'grass'], half: ['fire', 'water', 'ice', 'steel'], zero: [] },
  grass: { double: ['fire', 'ice', 'poison', 'flying', 'bug'], half: ['water', 'grass', 'electric', 'ground'], zero: [] },
  electric: { double: ['ground'], half: ['electric', 'flying', 'steel'], zero: [] },
  ice: { double: ['fire', 'fighting', 'rock', 'steel'], half: ['ice'], zero: [] },
  fighting: { double: ['flying', 'psychic', 'fairy'], half: ['bug', 'rock', 'dark'], zero: [] },
  poison: { double: ['ground', 'psychic'], half: ['grass', 'fighting', 'poison', 'bug', 'fairy'], zero: [] },
  ground: { double: ['water', 'grass', 'ice'], half: ['poison', 'rock'], zero: ['electric'] },
  flying: { double: ['electric', 'ice', 'rock'], half: ['grass', 'fighting', 'bug'], zero: ['ground'] },
  psychic: { double: ['bug', 'ghost', 'dark'], half: ['fighting', 'psychic'], zero: [] },
  bug: { double: ['fire', 'flying', 'rock'], half: ['grass', 'fighting', 'ground'], zero: [] },
  rock: { double: ['water', 'grass', 'fighting', 'ground', 'steel'], half: ['normal', 'fire', 'poison', 'flying'], zero: [] },
  ghost: { double: ['ghost', 'dark'], half: ['poison', 'bug'], zero: ['normal', 'fighting'] },
  dragon: { double: ['ice', 'dragon', 'fairy'], half: ['fire', 'water', 'grass', 'electric'], zero: [] },
  dark: { double: ['fighting', 'bug', 'fairy'], half: ['ghost', 'dark'], zero: ['psychic'] },
  steel: { double: ['fire', 'fighting', 'ground'], half: ['normal', 'grass', 'ice', 'flying', 'psychic', 'bug', 'rock', 'dragon', 'steel', 'fairy'], zero: ['poison'] },
  fairy: { double: ['poison', 'steel'], half: ['fighting', 'bug', 'dark'], zero: ['dragon'] },
};
